apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
# will need to get your own stripe api key
  STRIPE_KEY: eW91cktleUhlcmU=

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: eW91cktleUhlcmU=

